import type { SlashCommandOption } from '../components/work-items/AtReferenceTextarea';

const CLAUDE_CODE_COMMANDS: SlashCommandOption[] = [
  { command: 'add-dir', description: 'Add another working directory to the session.' },
  { command: 'bug', description: 'Report a Claude Code bug.' },
  { command: 'clear', description: 'Clear the current conversation context.' },
  { command: 'compact', description: 'Compress the conversation to save context.' },
  { command: 'config', description: 'Inspect and edit Claude Code configuration.' },
  { command: 'cost', description: 'Show token and cost usage for the session.' },
  { command: 'doctor', description: 'Run environment and installation diagnostics.' },
  { command: 'help', description: 'Show available Claude Code commands.' },
  { command: 'hooks', description: 'Manage Claude Code hooks.' },
  { command: 'init', description: 'Generate a CLAUDE.md or project guidance file.' },
  { command: 'login', description: 'Sign in to Claude Code.' },
  { command: 'logout', description: 'Sign out of Claude Code.' },
  { command: 'mcp', description: 'Inspect connected MCP servers and tools.' },
  { command: 'memory', description: 'Manage Claude Code memory.' },
  { command: 'model', description: 'Switch the active model.' },
  { command: 'permissions', description: 'Review or change permission behavior.' },
  { command: 'pr_comments', description: 'Work with pull request comments.' },
  { command: 'review', description: 'Review the current changes.' },
  { command: 'status', description: 'Show current session status.' },
  { command: 'terminal-setup', description: 'Configure terminal keybindings for multiline input.' },
  { command: 'vim', description: 'Toggle vim keybindings.' },
];

const GEMINI_COMMANDS: SlashCommandOption[] = [
  { command: 'about', description: 'Show Gemini CLI version and environment info.' },
  { command: 'agents', description: 'Manage available Gemini agents.' },
  { command: 'agents list', description: 'List available local and remote agents.' },
  { command: 'agents enable', description: 'Enable an installed agent.' },
  { command: 'agents disable', description: 'Disable an installed agent.' },
  { command: 'agents config', description: 'Open configuration for a specific agent.' },
  { command: 'auth', description: 'Authenticate an OAuth-enabled MCP server.' },
  { command: 'bug', description: 'Submit a Gemini CLI bug report.' },
  { command: 'chat', description: 'Save, resume, and share conversation checkpoints.' },
  { command: 'chat list', description: 'List saved conversation checkpoints.' },
  { command: 'chat save', description: 'Save the current conversation as a checkpoint.' },
  { command: 'chat resume', description: 'Resume a saved conversation checkpoint.' },
  { command: 'chat delete', description: 'Delete a saved conversation checkpoint.' },
  { command: 'chat share', description: 'Export the current conversation.' },
  { command: 'clear', description: 'Clear the screen and conversation history.' },
  { command: 'compress', description: 'Replace current context with a summary.' },
  { command: 'copy', description: 'Copy the latest result or code block.' },
  { command: 'corgi', description: 'Toggle corgi mode.' },
  { command: 'directory', description: 'Manage workspace directories.' },
  { command: 'docs', description: 'Open Gemini CLI docs in the browser.' },
  { command: 'editor', description: 'Set the external editor preference.' },
  { command: 'extensions', description: 'Manage Gemini CLI extensions.' },
  { command: 'help', description: 'Show Gemini CLI help.' },
  { command: 'hooks', description: 'Inspect and manage hooks.' },
  { command: 'hooks panel', description: 'Show all registered hooks and their status.' },
  { command: 'hooks enable', description: 'Enable a hook.' },
  { command: 'hooks disable', description: 'Disable a hook.' },
  { command: 'ide', description: 'Manage IDE integration.' },
  { command: 'init', description: 'Generate a tailored GEMINI.md file.' },
  { command: 'mcp', description: 'Manage configured MCP servers.' },
  { command: 'mcp auth', description: 'Authenticate an MCP server that uses OAuth.' },
  { command: 'memory', description: 'Inspect or update Gemini memory.' },
  { command: 'model', description: 'Configure the active model.' },
  { command: 'permissions', description: 'Manage folder trust and permissions.' },
  { command: 'plan', description: 'Switch into Plan mode.' },
  { command: 'policies', description: 'Inspect active policy rules.' },
  { command: 'policies list', description: 'List active policies grouped by mode.' },
  { command: 'privacy', description: 'Show the privacy notice.' },
  { command: 'profile', description: 'Toggle debug profile display.' },
  { command: 'quit', description: 'Exit Gemini CLI.' },
  { command: 'restore', description: 'Restore a previous tool call state.' },
  { command: 'resume', description: 'Browse and resume saved conversations.' },
  { command: 'rewind', description: 'Jump back to an earlier message.' },
  { command: 'settings', description: 'View and edit Gemini settings.' },
  { command: 'shells', description: 'Toggle the background shells view.' },
  { command: 'shortcuts', description: 'Toggle the shortcuts panel.' },
  { command: 'skills', description: 'List, enable, disable, or reload skills.' },
  { command: 'skills list', description: 'List available skills.' },
  { command: 'skills enable', description: 'Enable a skill.' },
  { command: 'skills disable', description: 'Disable a skill.' },
  { command: 'skills reload', description: 'Reload installed skills.' },
  { command: 'stats', description: 'Show session, model, or tool stats.' },
  { command: 'stats session', description: 'Show session stats.' },
  { command: 'stats model', description: 'Show model usage stats.' },
  { command: 'stats tools', description: 'Show tool usage stats.' },
  { command: 'terminal-setup', description: 'Configure terminal keybindings for multiline input.' },
  { command: 'theme', description: 'Change the CLI theme.' },
  { command: 'tools', description: 'List available Gemini CLI tools.' },
  { command: 'vim', description: 'Toggle vim mode.' },
];

const CODEX_COMMANDS: SlashCommandOption[] = [
  { command: 'approvals', description: 'Inspect or update approval behavior.' },
  { command: 'clear', description: 'Clear the terminal and start a new chat.' },
  { command: 'compact', description: 'Summarize the conversation to save context.' },
  { command: 'copy', description: 'Copy the latest Codex output.' },
  { command: 'diff', description: 'Show the current git diff, including untracked files.' },
  { command: 'fast', description: 'Toggle fast mode.' },
  { command: 'fork', description: 'Fork the current chat into a new thread.' },
  { command: 'init', description: 'Create an AGENTS.md file with project instructions.' },
  { command: 'mcp', description: 'List configured MCP tools.' },
  { command: 'model', description: 'Choose the model and reasoning effort.' },
  { command: 'new', description: 'Start a new chat.' },
  { command: 'permissions', description: 'Choose what Codex is allowed to do.' },
  { command: 'plan', description: 'Switch to Plan mode.' },
  { command: 'realtime', description: 'Toggle realtime voice mode.' },
  { command: 'resume', description: 'Resume a saved chat.' },
  { command: 'review', description: 'Review current changes and find issues.' },
  { command: 'sandbox-add-read-dir', description: 'Grant sandbox read access to an extra directory.' },
  { command: 'skills', description: 'Enable or disable skills.' },
  { command: 'status', description: 'Show current session configuration and token usage.' },
  { command: 'statusline', description: 'Configure which items appear in the status line.' },
  { command: 'theme', description: 'Choose a syntax highlighting theme.' },
];

const COMMANDS_BY_AGENT: Record<string, SlashCommandOption[]> = {
  'claude-code': CLAUDE_CODE_COMMANDS,
  'gemini-cli': GEMINI_COMMANDS,
  'codex-cli': CODEX_COMMANDS,
};

export function getAgentCliCommands(agentId: string | null | undefined): SlashCommandOption[] {
  if (!agentId) {
    return [];
  }

  return COMMANDS_BY_AGENT[agentId] ?? [];
}
